-- No-op: birth_year and gender were added to voters here but dropped in
-- migration 0025 before this branch shipped. Net effect on voters is zero.
-- Ballot-level demographic storage (ballot_demographics) was added in 0024.
